services:

  # DATABASE
  db: 
    image: mysql:8.3
    restart: always
    environment:
      MYSQL_DATABASE: cinema
      MYSQL_ROOT_PASSWORD: admincinema
    ports:
      - 3306:3306
    volumes:
      - ./back/laravel/mysql_data:/var/lib/mysql

  # ADMINER
  adminer:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - "8080:8080"

  # LARAVEL
  laravel:
    build: ./back/laravel
    ports:
      - 8000:8000
    volumes:
      - ./back/laravel:/var/www/
    working_dir: /var/www/
    depends_on:
      - db
    command: bash -c 'composer update && php artisan serve --host=0.0.0.0'

  # NUXT
  nuxt:
    build: 
      context: ./front
    ports:
      - 3000:3000
    volumes:
      - ./front:/app
    depends_on:
      - laravel
    environment:
      NUXT_APP_API_URL: http://laravel:8000
      CHOKIDAR_USEPOLLING: true
    command: bash -c "npm install && npm run dev"