services:

  db: 
    image: mysql:8.2.0
    restart: always
    environment:
      MYSQL_DATABASE: cinema
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    ports:
      - 3306:3306
    volumes:
      - ./back/mysql_data:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - "8080:8080"

  laravel:
    build: ./back/laravel
    ports:
      - 8000:8000
    volumes:
      - ./back/laravel:/var/www/
    working_dir: /var/www/
    depends_on:
      - db
    command: bash -c 'composer update && php artisan serve --host=0.0.0.0'